### ISSUE TITLE
Affix sidebar so it's always visible

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#425]
Currently, the sidebar scrolls away as you scroll down a page, but it should be "fixed" in position so it's always visible, even when you scroll down the page...

![2017-07-25_1604](https://user-images.githubusercontent.com/2925364/28597528-3a0ab65c-7153-11e7-9c6e-d9488d2f885b.png)

The sidebar is in `_layouts/default.html` and the code is:
```
        <nav class="col-md-3 sidebar-col">
          {% include sidebar.html %}
        </nav>
```

The ostensible way to do this would be to just add `position: fixed` to the CSS, or to use the Bootstrap [affix plugin](https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-affix.php) to "pin" it in place.  However, both of these screw up the layout as follows (with BS/affix it only occurs when you scroll down, with regular CSS it occurs immediately):

![2017-07-25_1612](https://user-images.githubusercontent.com/2925364/28597661-0c126abe-7154-11e7-89c0-fefd28950257.png)

Are  there any CSS gurus out there who can help with this?

**Comment by christophherr** [comment]
If you set the sidebar (.col-md-3) to position fixed, you could add margin-left: 25% to .col-md-9 
or you could add the bootstrap class pull-right to the markup.

**Comment by crandmck** [comment]
Thanks for the tips, @christophherr 
It works well when the page is wide, but as  you make it narrower, not so much:
![2017-09-05_1448](https://user-images.githubusercontent.com/2925364/30084957-5fad6e7e-9249-11e7-9ae8-dcbbacf931bc.png)

Any ideas on how to fix this?  Check out the `fix-sidebar` branch.  You can fork it if you can fix it and then open a PR, or just tell me how... Thanks very much!

Also, ideally the sidebar would display its own vertical scrollbar when it's expanded below the bottom of the page, which I tried to do with `overflow-y: auto;` but it didn't seem to work.

**Comment by christophherr** [comment]
@crandmck Thanks for testing my suggestions. 

It's probably better to go with the margin-left idea.
If you ever update to Bootstrap 4, the .pull-right class won't work anymore.

Is this what you had in mind? 
https://d.pr/v/BKXTV

Here is the code used in the screencast (this is without pull-right in the markup):
```css

@media (min-width: 992px) {
    .col-md-3 {
        height: 100%;
        overflow-y: auto;
        position: fixed;
        width: 26%;
        z-index: 999;
    }
    .col-md-9 {
        margin-left: 28%;
    }
}

@media (min-width: 1065px) {
    .col-md-3 {
        width: 24%;
    }
}

@media (min-width: 1115px) {
    .col-md-3 {
        width: 23%;
    }
}

@media (min-width: 1230px) {
    .col-md-3 {
        width: 21%;
    }
}
```

Is there a preferred file to add CSS changes to?
I can open a PR tomorrow. I have to stop my editor from auto formatting...
